# Generated by Django 2.2.7 on 2019-12-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_id', models.CharField(max_length=100)),
                ('comment_text', models.CharField(max_length=300)),
                ('create_date_time', models.DateTimeField()),
                ('rank', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='WebToon',
            fields=[
                ('webtoon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('webtoon_name', models.CharField(max_length=200)),
                ('webtoon_author', models.CharField(max_length=100)),
                ('webtoon_img_url', models.CharField(max_length=300)),
                ('webtoon_views', models.IntegerField(default=0)),
                ('webtoon_update', models.IntegerField(default=0)),
                ('webtoon_status', models.IntegerField(default=0)),
                ('webtoon_mon', models.IntegerField(default=0)),
                ('webtoon_tue', models.IntegerField(default=0)),
                ('webtoon_wed', models.IntegerField(default=0)),
                ('webtoon_thu', models.IntegerField(default=0)),
                ('webtoon_fri', models.IntegerField(default=0)),
                ('webtoon_sat', models.IntegerField(default=0)),
                ('webtoon_sun', models.IntegerField(default=0)),
            ],
        ),
    ]
